title: Interaction Integration
url: "https://jjycavailles.github.io/"
google_analytics: G-VPTWJKGKTG
lang: en
permalink: '/:title/'
collections:
  posts:
    permalink: './posts/:title/'
layout_type: boxed
style: classic
palette: 007000
mode: light
base_font: serif
header:
  has_primary_nav: true
  primary_nav_links:
    text_align: left
    t:
      en:
          - label: Home
            url: ./
            style: link
          - label: About me
            url: ./me
            style: link
      fr:
          - label: Accueil
            url: ./index_fr
            style: link
          - label: Moi
            url: ./moi
            style: link
  has_secondary_nav: false
  has_anncmnt: false
footer:
  has_primary_nav: true
  primary_nav_links:
    - label: Resume
      url: ./resume
      style: link
    - label: Research
      url: ./research
      style: link
    - label: Blog
      url: ./blog
      style: link
  has_secondary_nav: true
  secondary_nav_links:
    - label: Style Guide
      url: /style-guide
      style: link
    - label: Terms & Conditions
      url: /terms-conditions
      style: link
    - label: Privacy Policy
      url: /privacy-policy
      style: link
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/CavaillesJerome'
      style: link
      has_icon: true
      icon: twitter
      icon_position: center
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/in/jeromecavailles/'
      style: link
      has_icon: true
      icon: linkedin
      icon_position: center
      new_window: true
    - label: Github
      url: 'https://github.com/jjycavailles/'
      style: link
      has_icon: true
      icon: github
      icon_position: center
      new_window: true
sass:
  indentWidth: 4
  style: expanded
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
